{
  categories {
    id
    name
    slug
    active
    is_default
    photo
    created_at
    updated_at
    locations {
        id
        name
        slug
        category_id
        website
        address
        city
        state
        zip
        latitude
        longitude
        description
        photo
        tags {
            name
            slug
        }
        is_family_friendly
        created_at
        updated_at
    }
    events {
        id
        name
        slug
        location_id
        user_id
        category_id
        event_type_id
        start_date
        end_date
        price
        start_time
        end_time
        short_description
        description
        featured
        active
        is_sold_out
        website
        spotify_artist_id
        is_family_friendly
        photo
        category {
            name
            slug
        }
        event_type
        tags {
            name
            slug
        }
    }
  }
}