query eventsByLocation($location: String!) {
  eventsByLocation(location: $location) {
    id
    name
    slug
    location_id
    user_id
    category_id
    event_type_id
    start_date
    end_date
    price
    start_time
    end_time
    short_description
    description
    featured
    is_sold_out
    website
    is_family_friendly
    photo
    category {
        name
        slug
    }
    event_type
    tags {
        name
        slug
    }
    location {
        id
        name
        slug
        category_id
        website
        address
        city
        state
        zip
        latitude
        longitude
        description
        photo
        tags {
            name
            slug
        }
        created_at
        updated_at
    }
    bands {
        id
        name
        slug
        photo
    }
  }
}