query locationBySlug($slug: String!) {
  locationBySlug(slug: $slug) {
    id
    name
    slug
    category_id
    website
    address
    city
    state
    zip
    latitude
    longitude
    description
    created_at
    updated_at
    category { id, name, active, is_default, created_at, updated_at }
  }
}