query locationBySlug($slug: String!) {
  locationBySlug(slug: $slug) {
    id
    name
    slug
    category_id
    website
    address
    city
    state
    zip
    latitude
    longitude
    description
    photo
    thumb_small
    thumb_medium
    tags {
        name
        slug
    }
    is_family_friendly
    created_at
    updated_at
    category {
        id
        name
        slug
        is_default
        photo
        created_at
        updated_at
    }
  }
}