{
  locations {
    id
    name
    slug
    category_id
    website
    address
    city
    state
    zip
    latitude
    longitude
    description
    photo
    tags {
        name
        slug
    }
    is_family_friendly
    created_at
    updated_at
    category {
        id
        name
        slug
        active
        is_default
        photo
        created_at
        updated_at
    }
  }
}