mutation register($name: String!, $email: String!, $password: String!){
  register(name: $name, email: $email, password: $password) {
    token
    user {
      id
      name
      email
      created_at
      updated_at
    }
  }
}
